artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/d92cff595db94af2b43dfa632faca7c5/artifacts
end_time: 1757412460178
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: d92cff595db94af2b43dfa632faca7c5
run_name: judicious-hawk-831
source_name: ''
source_type: 4
source_version: ''
start_time: 1757412452412
status: 3
tags: []
user_id: imvaibhavrana
