artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/aa6dda5df95748a2876b9eb91392ece5/artifacts
end_time: 1757411176998
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: aa6dda5df95748a2876b9eb91392ece5
run_name: capricious-roo-790
source_name: ''
source_type: 4
source_version: ''
start_time: 1757411176788
status: 3
tags: []
user_id: imvaibhavrana
