artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/f5e91262d265492cbdd1dddef63494db/artifacts
end_time: 1757411481140
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: f5e91262d265492cbdd1dddef63494db
run_name: intrigued-lynx-249
source_name: ''
source_type: 4
source_version: ''
start_time: 1757411479051
status: 3
tags: []
user_id: imvaibhavrana
