artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/7d6c3786d0ba4c278ddb459cbd9f46f6/artifacts
end_time: 1757394462907
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: 7d6c3786d0ba4c278ddb459cbd9f46f6
run_name: agreeable-hen-248
source_name: ''
source_type: 4
source_version: ''
start_time: 1757394462893
status: 4
tags: []
user_id: imvaibhavrana
