artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/1cba566db53c4edeaa98218bde1e6c00/artifacts
end_time: 1757411177216
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: 1cba566db53c4edeaa98218bde1e6c00
run_name: unruly-pug-469
source_name: ''
source_type: 4
source_version: ''
start_time: 1757411177011
status: 3
tags: []
user_id: imvaibhavrana
