artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/c8ecba462045444c8fbe82a94caea13c/artifacts
end_time: 1757411153568
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: c8ecba462045444c8fbe82a94caea13c
run_name: receptive-trout-754
source_name: ''
source_type: 4
source_version: ''
start_time: 1757411153529
status: 3
tags: []
user_id: imvaibhavrana
