artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/f6dca24e06444376a2cec364df8507ca/artifacts
end_time: 1757394548268
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: f6dca24e06444376a2cec364df8507ca
run_name: incongruous-hog-575
source_name: ''
source_type: 4
source_version: ''
start_time: 1757394548249
status: 4
tags: []
user_id: imvaibhavrana
