artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/d24033c0dad3471ebd9f7c660e1f8a98/artifacts
end_time: 1757394979780
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: d24033c0dad3471ebd9f7c660e1f8a98
run_name: kindly-loon-412
source_name: ''
source_type: 4
source_version: ''
start_time: 1757394979562
status: 4
tags: []
user_id: imvaibhavrana
