artifact_uri: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/886638330577656943/a051b0ecfb6e45f692eed6d670e0194b/artifacts
end_time: 1757394426832
entry_point_name: ''
experiment_id: '886638330577656943'
lifecycle_stage: active
run_id: a051b0ecfb6e45f692eed6d670e0194b
run_name: caring-squid-382
source_name: ''
source_type: 4
source_version: ''
start_time: 1757394426812
status: 4
tags: []
user_id: imvaibhavrana
