artifact_location: /home/imvaibhavrana/mlops/02-experiment-tracking/$MLFLOW_DB_URI/0
creation_time: 1757386861658
experiment_id: '0'
last_update_time: 1757386861658
lifecycle_stage: active
name: Default
